version: '3'

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=tarefas
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
  
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    